#!/usr/bin/env bash
#
# ############################################################################
# Project: polybarctl (vundefined)
# File...: polybarctl
# Created: Monday, 2023/03/06 - 01:14:37
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2023/03/23 - 18:40:26
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.7.70
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# shellcheck disable=SC1090,SC2154
#   * SC1090: Can't follow non-constant source. Use a directive to specify location.
#       -> cant follow or source usage
#   * SC2154: var is referenced but not assigned.
#       -> variables created by or library system (don't worry)

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
source ~/bin/xSHELL/init
use args polybar.lib

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xrequirements git polybar

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xarg --id -i,--install    --var action:i               --desc "install polybar themes (by adi1090x)"
xarg --id -l,--list       --var action:l               --desc "list available themes"
xarg --id -r,--run        --var action:r,theme+r,bar+o --desc "run one available <theme> or a given config_file (<bar> is optional when using a custom config file)"
xarg --id -s,--status     --var action:s               --desc "show polybar status on system"
xarg --id -q,--quit       --var action:q               --desc "quit all polybar instances"
xarg --id -u,--uninstall  --var action:u               --desc "uninstall polybar themes"

xarg --header "Simple script to manage polybar and install/run themes created by @adi1090x"

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xrun --xreject-unknow --xrequire-one --xcolors --xversionrc "$@"

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
case "$action" in
  i) pInstall      ;;
  l) pList         ;;
  r) pRun "$theme" ;;
  s) pStatus       ;;
  u) pUninstall    ;;
  q) pQuit         ;;
esac
